# Generated by Django 4.0.4 on 2022-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('espece', models.CharField(max_length=100)),
                ('type', models.JSONField()),
                ('pokemon_legendaire', models.BooleanField()),
                ('pokemon_mythique', models.BooleanField()),
            ],
        ),
    ]
