# Generated by Django 4.0.4 on 2022-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_pokemon_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
