# Generated by Django 4.0.4 on 2022-06-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0004_remove_pokemon_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='espece',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_legendaire',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_mythique',
        ),
    ]
